admin_name: "admin"
admin_password: "admin"
domain: "api.doamin.com"
static_path: "C:/modernboard-static/"
environment: test
cert_dir: "secret-dir"
database_url: "postgres://mb:mb@localhost:5432/modernboard?sslmode=disable"
default_salt: "fmsf%!**$234@"
max_image_size_mb: 10